[package]
name = "bevy_mod_osc"
version = "0.1.8"
edition = "2021"

readme = "README.md"
description = "OSC plugin for Bevy engine"
license = "WTFPL"
authors = ["Fumiya Funatsu <funatsu.fumiya@gmail.com>"]
repository = "https://github.com/funatsufumiya/bevy_mod_osc"
keywords = ["osc"]

[dev-dependencies]
# bevy = "0.13"

[dependencies]
bevy = { version = "0.13", default-features = false, features = ["bevy_asset", "multi-threaded"]}
bevy_async_task = "0.1"
rosc = "~0.10"
chrono = "0.4.19"
async-std = "1.12.0"
lazy_static = "1.4.0"
